### ISSUE TITLE
server connection 

### ISSUE THREAD

**Issue by Thordekk** [V-Cyberpunk/Aloys-Launcher#2]
how we get this? USE a valid certificate matching your authentication/bnet server host name.
i have host in other pc so how i can connect?

**Comment by V-Cyberpunk** [comment]
own certs currently not working. i will do this, if  i had time for this. i have the theory and need to implement it. forgot to write this in readme.

**Comment by V-Cyberpunk** [comment]
i read it again. this is from the original project. ok, if you havve, for example login.example.net as your wow server login domain, you need a valid tls cert for this domain.
